name: Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install, Build
        run: |
          yarn
          npx lerna bootstrap
          yarn build
          yarn build:storybook
          yarn build:docs
