name: Verify
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Prepare
        run: |
          yarn
          npx lerna bootstrap
      - name: Build
        run: |
          yarn build:all-targets
          yarn build:storybook
          yarn build:docs
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
